; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1250 -passes=separate-const-offset-from-gep -S %s | FileCheck %s

; Tests for the padded-layout address rewriting in SeparateConstOffsetFromGEP.
; A padded shared-memory layout computes physical addresses as:
;   physical = logical_addr + padding(logical_addr)
; where padding(addr) = and(lshr(addr, shift), mask).
;
; When logical_addr = or_disjoint(base, C), the padding term contains a hidden
; constant (C >> shift) & mask that this pass should extract.

@global_smem = external addrspace(3) global [0 x i8], align 16

; Test rewritePaddedLayoutAddrInGEP: single GEP index with full padded address
; pattern add(and(lshr(V, s), mask), V) where V = or_disjoint(base, C).
; Multiple loads with different C values should share the same variable base.
define void @padded_layout_single_index(ptr addrspace(1) writeonly %out, i32 %idx) {
; CHECK-LABEL: define void @padded_layout_single_index(
; CHECK-SAME: ptr addrspace(1) writeonly [[OUT:%.*]], i32 [[IDX:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[BASE:%.*]] = shl nuw nsw i32 [[IDX]], 7
; CHECK-NEXT:    [[TMP0:%.*]] = lshr exact i32 [[BASE]], 4
; CHECK-NEXT:    [[TMP1:%.*]] = and i32 [[TMP0]], 134217712
; CHECK-NEXT:    [[TMP2:%.*]] = add i32 [[TMP1]], [[BASE]]
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr addrspace(3) @global_smem, i32 [[TMP2]]
; CHECK-NEXT:    [[GEP11:%.*]] = getelementptr i8, ptr addrspace(3) [[TMP3]], i32 4352
; CHECK-NEXT:    [[LOAD1:%.*]] = load <16 x i8>, ptr addrspace(3) [[GEP11]], align 16
; CHECK-NEXT:    [[TMP4:%.*]] = lshr exact i32 [[BASE]], 4
; CHECK-NEXT:    [[TMP5:%.*]] = and i32 [[TMP4]], 134217712
; CHECK-NEXT:    [[TMP6:%.*]] = add i32 [[TMP5]], [[BASE]]
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr addrspace(3) @global_smem, i32 [[TMP6]]
; CHECK-NEXT:    [[GEP22:%.*]] = getelementptr i8, ptr addrspace(3) [[TMP7]], i32 4384
; CHECK-NEXT:    [[LOAD2:%.*]] = load <16 x i8>, ptr addrspace(3) [[GEP22]], align 16
; CHECK-NEXT:    [[COMBINED:%.*]] = shufflevector <16 x i8> [[LOAD1]], <16 x i8> [[LOAD2]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 16, i32 17, i32 18, i32 19, i32 4, i32 5, i32 6, i32 7, i32 20, i32 21, i32 22, i32 23>
; CHECK-NEXT:    store <16 x i8> [[COMBINED]], ptr addrspace(1) [[OUT]], align 16
; CHECK-NEXT:    ret void
;
entry:
  %base = shl nuw nsw i32 %idx, 7

  ; Load 1: C = 4096, shift = 4, mask = 134217712 (0x7FFFFF0)
  ; PaddingConst = (4096 >> 4) & 0x7FFFFF0 = 256
  ; TotalConst = 4096 + 256 = 4352
  %v1 = or disjoint i32 %base, 4096
  %s1 = lshr exact i32 %v1, 4
  %m1 = and i32 %s1, 134217712
  %idx1 = add nuw nsw i32 %m1, %v1
  %gep1 = getelementptr inbounds nuw i8, ptr addrspace(3) @global_smem, i32 %idx1
  %load1 = load <16 x i8>, ptr addrspace(3) %gep1, align 16

  ; Load 2: C = 4128, shift = 4, mask = 134217712
  ; PaddingConst = (4128 >> 4) & 0x7FFFFF0 = 256
  ; TotalConst = 4128 + 256 = 4384
  %v2 = or disjoint i32 %base, 4128
  %s2 = lshr exact i32 %v2, 4
  %m2 = and i32 %s2, 134217712
  %idx2 = add nuw nsw i32 %m2, %v2
  %gep2 = getelementptr inbounds nuw i8, ptr addrspace(3) @global_smem, i32 %idx2
  %load2 = load <16 x i8>, ptr addrspace(3) %gep2, align 16

  ; Use both loads to prevent DCE
  %combined = shufflevector <16 x i8> %load1, <16 x i8> %load2, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 16, i32 17, i32 18, i32 19, i32 4, i32 5, i32 6, i32 7, i32 20, i32 21, i32 22, i32 23>
  store <16 x i8> %combined, ptr addrspace(1) %out, align 16
  ret void
}

; Test rewritePaddingAdjustmentInGEP: two-level GEP chain where the padding
; adjustment and(lshr(or_disjoint(X, C), s), mask) is a separate GEP index.
; Multiple loads with different C values should share the same variable base.
define void @padded_layout_two_level_gep(ptr addrspace(1) writeonly %out, i32 %idx) {
; CHECK-LABEL: define void @padded_layout_two_level_gep(
; CHECK-SAME: ptr addrspace(1) writeonly [[OUT:%.*]], i32 [[IDX:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[BASE:%.*]] = shl nuw nsw i32 [[IDX]], 7
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(3) @global_smem, i32 [[BASE]]
; CHECK-NEXT:    [[TMP1:%.*]] = lshr exact i32 [[BASE]], 4
; CHECK-NEXT:    [[TMP2:%.*]] = and i32 [[TMP1]], 2800
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds i8, ptr addrspace(3) [[TMP0]], i32 [[TMP2]]
; CHECK-NEXT:    [[GEP1B3:%.*]] = getelementptr inbounds i8, ptr addrspace(3) [[TMP3]], i32 34816
; CHECK-NEXT:    [[LOAD1:%.*]] = load <16 x i8>, ptr addrspace(3) [[GEP1B3]], align 16
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(3) @global_smem, i32 [[BASE]]
; CHECK-NEXT:    [[TMP5:%.*]] = lshr exact i32 [[BASE]], 4
; CHECK-NEXT:    [[TMP6:%.*]] = and i32 [[TMP5]], 2800
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr inbounds i8, ptr addrspace(3) [[TMP4]], i32 [[TMP6]]
; CHECK-NEXT:    [[GEP2B6:%.*]] = getelementptr inbounds i8, ptr addrspace(3) [[TMP7]], i32 34848
; CHECK-NEXT:    [[LOAD2:%.*]] = load <16 x i8>, ptr addrspace(3) [[GEP2B6]], align 16
; CHECK-NEXT:    [[COMBINED:%.*]] = shufflevector <16 x i8> [[LOAD1]], <16 x i8> [[LOAD2]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 16, i32 17, i32 18, i32 19, i32 4, i32 5, i32 6, i32 7, i32 20, i32 21, i32 22, i32 23>
; CHECK-NEXT:    store <16 x i8> [[COMBINED]], ptr addrspace(1) [[OUT]], align 16
; CHECK-NEXT:    ret void
;
entry:
  %base = shl nuw nsw i32 %idx, 7

  ; Load 1: C = 32768, shift = 4, mask = 2800
  ; PaddingConst = (32768 >> 4) & 2800 = 2048
  ; GEP1 extracts 32768 from or_disjoint, GEP2 extracts 2048 from padding
  ; Total const = 32768 + 2048 = 34816
  %or1 = or disjoint i32 %base, 32768
  %shr1 = lshr exact i32 %or1, 4
  %pad1 = and i32 %shr1, 2800
  %gep1a = getelementptr inbounds nuw i8, ptr addrspace(3) @global_smem, i32 %or1
  %gep1b = getelementptr inbounds nuw i8, ptr addrspace(3) %gep1a, i32 %pad1
  %load1 = load <16 x i8>, ptr addrspace(3) %gep1b, align 16

  ; Load 2: C = 32800, shift = 4, mask = 2800
  ; PaddingConst = (32800 >> 4) & 2800 = 2048
  ; Total const = 32800 + 2048 = 34848
  %or2 = or disjoint i32 %base, 32800
  %shr2 = lshr exact i32 %or2, 4
  %pad2 = and i32 %shr2, 2800
  %gep2a = getelementptr inbounds nuw i8, ptr addrspace(3) @global_smem, i32 %or2
  %gep2b = getelementptr inbounds nuw i8, ptr addrspace(3) %gep2a, i32 %pad2
  %load2 = load <16 x i8>, ptr addrspace(3) %gep2b, align 16

  %combined = shufflevector <16 x i8> %load1, <16 x i8> %load2, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 16, i32 17, i32 18, i32 19, i32 4, i32 5, i32 6, i32 7, i32 20, i32 21, i32 22, i32 23>
  store <16 x i8> %combined, ptr addrspace(1) %out, align 16
  ret void
}

; Negative test: or without disjoint flag should NOT be rewritten.
define void @no_rewrite_without_disjoint(ptr addrspace(1) writeonly %out, i32 %idx) {
; CHECK-LABEL: define void @no_rewrite_without_disjoint(
; CHECK-SAME: ptr addrspace(1) writeonly [[OUT:%.*]], i32 [[IDX:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[BASE:%.*]] = shl nuw nsw i32 [[IDX]], 7
; CHECK-NEXT:    [[V:%.*]] = or i32 [[BASE]], 4096
; CHECK-NEXT:    [[S:%.*]] = lshr i32 [[V]], 4
; CHECK-NEXT:    [[M:%.*]] = and i32 [[S]], 134217712
; CHECK-NEXT:    [[ADDR:%.*]] = add i32 [[M]], [[V]]
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(3) @global_smem, i32 [[ADDR]]
; CHECK-NEXT:    [[LOAD:%.*]] = load <16 x i8>, ptr addrspace(3) [[GEP]], align 16
; CHECK-NEXT:    store <16 x i8> [[LOAD]], ptr addrspace(1) [[OUT]], align 16
; CHECK-NEXT:    ret void
;
entry:
  %base = shl nuw nsw i32 %idx, 7
  %v = or i32 %base, 4096
  %s = lshr i32 %v, 4
  %m = and i32 %s, 134217712
  %addr = add i32 %m, %v
  %gep = getelementptr inbounds nuw i8, ptr addrspace(3) @global_smem, i32 %addr
  %load = load <16 x i8>, ptr addrspace(3) %gep, align 16
  store <16 x i8> %load, ptr addrspace(1) %out, align 16
  ret void
}

; Negative test: zero constant in or_disjoint should NOT be rewritten.
define void @no_rewrite_zero_const(ptr addrspace(1) writeonly %out, i32 %idx) {
; CHECK-LABEL: define void @no_rewrite_zero_const(
; CHECK-SAME: ptr addrspace(1) writeonly [[OUT:%.*]], i32 [[IDX:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[BASE:%.*]] = shl nuw nsw i32 [[IDX]], 7
; CHECK-NEXT:    [[V:%.*]] = or disjoint i32 [[BASE]], 0
; CHECK-NEXT:    [[S:%.*]] = lshr exact i32 [[V]], 4
; CHECK-NEXT:    [[M:%.*]] = and i32 [[S]], 134217712
; CHECK-NEXT:    [[ADDR:%.*]] = add nuw nsw i32 [[M]], [[V]]
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(3) @global_smem, i32 [[ADDR]]
; CHECK-NEXT:    [[LOAD:%.*]] = load <16 x i8>, ptr addrspace(3) [[GEP]], align 16
; CHECK-NEXT:    store <16 x i8> [[LOAD]], ptr addrspace(1) [[OUT]], align 16
; CHECK-NEXT:    ret void
;
entry:
  %base = shl nuw nsw i32 %idx, 7
  %v = or disjoint i32 %base, 0
  %s = lshr exact i32 %v, 4
  %m = and i32 %s, 134217712
  %addr = add nuw nsw i32 %m, %v
  %gep = getelementptr inbounds nuw i8, ptr addrspace(3) @global_smem, i32 %addr
  %load = load <16 x i8>, ptr addrspace(3) %gep, align 16
  store <16 x i8> %load, ptr addrspace(1) %out, align 16
  ret void
}

; Negative test for standalone padding: PaddingConst = 0 should NOT be rewritten.
; C = 15, shift = 4, mask = 134217712 → (15 >> 4) & mask = 0
define void @no_rewrite_zero_padding_const(ptr addrspace(1) writeonly %out, i32 %idx) {
; CHECK-LABEL: define void @no_rewrite_zero_padding_const(
; CHECK-SAME: ptr addrspace(1) writeonly [[OUT:%.*]], i32 [[IDX:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[BASE:%.*]] = shl nuw nsw i32 [[IDX]], 7
; CHECK-NEXT:    [[OR:%.*]] = or disjoint i32 [[BASE]], 15
; CHECK-NEXT:    [[SHR:%.*]] = lshr exact i32 [[OR]], 4
; CHECK-NEXT:    [[PAD:%.*]] = and i32 [[SHR]], 134217712
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(3) @global_smem, i32 [[BASE]]
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(3) [[TMP0]], i32 [[PAD]]
; CHECK-NEXT:    [[GEP23:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(3) [[TMP1]], i32 15
; CHECK-NEXT:    [[LOAD:%.*]] = load <16 x i8>, ptr addrspace(3) [[GEP23]], align 16
; CHECK-NEXT:    store <16 x i8> [[LOAD]], ptr addrspace(1) [[OUT]], align 16
; CHECK-NEXT:    ret void
;
entry:
  %base = shl nuw nsw i32 %idx, 7
  %or = or disjoint i32 %base, 15
  %shr = lshr exact i32 %or, 4
  %pad = and i32 %shr, 134217712
  %gep1 = getelementptr inbounds nuw i8, ptr addrspace(3) @global_smem, i32 %or
  %gep2 = getelementptr inbounds nuw i8, ptr addrspace(3) %gep1, i32 %pad
  %load = load <16 x i8>, ptr addrspace(3) %gep2, align 16
  store <16 x i8> %load, ptr addrspace(1) %out, align 16
  ret void
}
